"""add tables to database

Revision ID: 57a68a917a5e
Revises: 
Create Date: 2023-08-12 16:45:50.874503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '57a68a917a5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('floater', sa.Boolean(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('assigned', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sqlite.DATE(), nullable=False),
    sa.Column('swappout_id', sa.Integer(), nullable=True),
    sa.Column('vol_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_schedules_role_id_roles')),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteers.id'], name=op.f('fk_schedules_vol_id_volunteers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_role',
    sa.Column('vol_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_volunteer_role_role_id_roles')),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteers.id'], name=op.f('fk_volunteer_role_vol_id_volunteers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_role')
    op.drop_table('schedules')
    op.drop_table('volunteers')
    op.drop_table('roles')
    # ### end Alembic commands ###
